<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-G0IG718" failures="1" tests="1" name="validTest" time="15.168" errors="0" timestamp="2024-02-14T04:10:08 IST">
  <testcase classname="test.ValidUrl" name="validUrlTest" time="14.104">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.ValidUrl.validUrlTest(ValidUrl.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- validUrlTest -->
  <testcase classname="test.ValidUrl" name="testInvalidUrl" time="0.0">
    <ignored/>
  </testcase> <!-- testInvalidUrl -->
  <testcase classname="test.ValidUrl" name="OtherDomainValidUrl" time="0.0">
    <ignored/>
  </testcase> <!-- OtherDomainValidUrl -->
</testsuite> <!-- validTest -->
